const SOURCES=[['Adorio','https://www.adorio.hr/poslovi.php'],['Pick Jobs','https://pick.jobs/hr'],['Jooble Hrvatska','https://hr.jooble.org/'],['Moj Posao','https://www.moj-posao.net/'],['Bika','https://www.bika.net/poslovi'],['Freelance.hr','https://www.freelance.hr/hr'],['Oglasnik','https://www.oglasnik.hr/posao'],['Posao.hr','https://www.posao.hr/']];
const FB=[['NUDIM–TRAŽIM POSAO/ZAGREB','Grupo privado'],['Latinos en Croacia','Grupo privado'],['TRAŽIM–NUDIM POSAO','Grupo público']];
const DEFAULT={freeAccommodation:true,permit:true,salary:1200,contract:false,thirdCountry:true,company50:false};
let state=JSON.parse(localStorage.getItem('cja-state')||'null')||{filters:DEFAULT,jobs:[],applications:[],cvName:'CV croata — versión preparada',lastSearch:null};
function save(){localStorage.setItem('cja-state',JSON.stringify(state))}
function nav(view){document.querySelectorAll('.nav').forEach(b=>b.classList.toggle('active',b.dataset.view===view));document.querySelectorAll('.view').forEach(v=>v.classList.toggle('active',v.id===view));const t={dashboard:'Panel',jobs:'Empleos',applications:'Candidaturas',company:'Empresas',settings:'Configuración'};document.getElementById('title').textContent=t[view];document.getElementById('subtitle').textContent=view==='dashboard'?'Encuentra oportunidades y prepara tus candidaturas':'Agente de empleo · filtros, investigación y autorización de envío';render()}
document.querySelectorAll('.nav').forEach(b=>b.onclick=()=>nav(b.dataset.view));
document.getElementById('searchBtn').onclick=()=>liveSearch();document.getElementById('closeModal').onclick=()=>closeModalDirect();
function dashboard(){const strong=state.jobs.filter(j=>j.status==='green').length;return `<div class="grid"><div class="stat"><b>${state.jobs.length}</b><span>Ofertas analizadas</span></div><div class="stat"><b>${strong}</b><span>Oportunidades fuertes</span></div><div class="stat"><b>${state.applications.length}</b><span>Candidaturas preparadas</span></div><div class="stat"><b>0</b><span>Enviadas sin autorización</span></div></div><div class="two"><div class="card"><div class="live">AGENTE CONFIGURADO</div><h2 style="margin-top:8px">Tus filtros principales</h2><div class="checks"><div class="check">🏠 <div><b>Alojamiento gratuito</b><br><span class="muted">Debe estar indicado como gratuito o asumido por el empleador; “smještaj osiguran” (alojamiento proporcionado) por sí solo no basta.</span></div></div><div class="check">📄 <div><b>Permiso de residencia y trabajo</b><br><span class="muted">Se busca evidencia de que el empleador puede gestionar el trámite para un ciudadano colombiano.</span></div></div></div></div><div class="card"><div class="live">FUENTES ACTIVAS</div><h2 style="margin-top:8px">Portales conectados</h2><div class="source-list">${SOURCES.map(x=>`<a class="source" target="_blank" href="${x[1]}">${x[0]} ↗</a>`).join('')}</div></div></div>`}
function badge(s){return `<span class="tag ${s}">${s==='green'?'🟢 Fuerte':s==='yellow'?'🟡 Potencial':s==='orange'?'🟠 Interesante':'🔴 Descartar'}</span>`}
function jobCard(j,i){return `<article class="job"><div class="job-head"><div>${badge(j.status)}<h3 style="margin-top:10px">${j.title}</h3><div class="pill">${j.company} · ${j.city} · ${j.source}</div></div><strong>${j.salary}</strong></div><div class="meta"><span>🏠 ${j.accommodation}</span><span>📄 ${j.permit}</span><span>🇨🇴 ${j.foreigner}</span></div><p>${j.note}</p><div class="actions"><button class="secondary" onclick="details(${i})">Ver evidencia</button><a class="secondary" target="_blank" href="${j.url}">Abrir oferta ↗</a><button class="primary" onclick="prepare(${i})">Preparar candidatura</button></div></article>`}
function jobs(){return `<div class="card" style="margin-bottom:14px"><div class="searchbar"><input id="queryInput" value="${state.lastSearch||'skladištar radnik smještaj dozvola'}" placeholder="Ej.: skladištar, radnik, smještaj, dozvola"><button class="primary" onclick="liveSearch()">Buscar ahora</button></div><div class="result-info">El buscador consulta las páginas públicas conectadas y después clasifica la evidencia. Los dos filtros principales siguen siendo obligatorios.</div></div>${state.jobs.length?`<div class="job-list">${state.jobs.map(jobCard).join('')}</div>`:`<div class="empty">Pulsa <b>Buscar nuevos empleos</b> para hacer una búsqueda real en las fuentes conectadas.</div>`}`}
function applications(){if(!state.applications.length)return `<div class="empty">Todavía no hay candidaturas preparadas.<br>En una oferta pulsa <b>Preparar candidatura</b>.</div>`;return `<div class="job-list">${state.applications.map((a,i)=>`<div class="card"><div class="job-head"><div><h3>${a.title}</h3><span class="muted">${a.company} · ${a.city}</span></div><span class="tag yellow">📝 Preparada — requiere autorización</span></div><div class="meta"><span>CV: ${a.cv}</span><span>Mensaje: solo croata</span></div><div class="actions"><button class="secondary" onclick="review(${i})">Revisar</button><button class="danger" onclick="authorize(${i})">Autorizar envío</button></div></div>`).join('')}</div>`}
function company(){return `<div class="card"><div class="live">INVESTIGACIÓN</div><h2 style="margin-top:8px">Empresas y experiencias de trabajadores</h2><p>La aplicación separa hechos encontrados en publicaciones/ofertas de comentarios anecdóticos. Los grupos privados de Facebook no se tratarán como fuentes accesibles automáticamente.</p><div class="source-grid">${FB.map(x=>`<div class="source"><b>${x[0]}</b><br><span class="muted">${x[1]} · acceso según disponibilidad</span></div>`).join('')}</div></div>`}
function settings(){return `<div class="card"><div class="live">PERFIL</div><h2 style="margin-top:8px">Perfil de candidatura</h2><div class="field"><label>CV que se adjuntará</label><input value="${state.cvName}" onchange="state.cvName=this.value;save();render()"></div><div class="field"><label>Email</label><input value="fabianramirezlopez216@gmail.com" readonly></div><div class="field"><label>Situación</label><input value="Ciudadano colombiano · actualmente fuera de Croacia" readonly></div><h3>Preferencias</h3><div class="checks"><label class="check"><input type="checkbox" ${state.filters.freeAccommodation?'checked':''} onchange="state.filters.freeAccommodation=this.checked;save()"> 🏠 Alojamiento gratuito</label><label class="check"><input type="checkbox" ${state.filters.permit?'checked':''} onchange="state.filters.permit=this.checked;save()"> 📄 Empleador gestiona residencia y trabajo</label><label class="check"><input type="checkbox" ${state.filters.thirdCountry?'checked':''} onchange="state.filters.thirdCountry=this.checked;save()"> 🇨🇴 Acepta ciudadanos de terceros países</label><label class="check"><input type="checkbox" ${state.filters.contract?'checked':''} onchange="state.filters.contract=this.checked;save()"> 📑 Contrato confirmado (preferencia)</label></div><div class="notice"><b>Regla de envío:</b> el mensaje que recibe la empresa es únicamente en croata y se adjunta el CV en croata. La traducción española solo se muestra para tu revisión.</div></div>`}
function render(){document.getElementById('dashboard').innerHTML=dashboard();document.getElementById('jobs').innerHTML=jobs();document.getElementById('applications').innerHTML=applications();document.getElementById('company').innerHTML=company();document.getElementById('settings').innerHTML=settings()}
async function liveSearch(){nav('jobs');const btn=document.getElementById('searchBtn');btn.disabled=true;btn.innerHTML='⏳ Buscando...';const q=(document.getElementById('queryInput')?.value||'skladištar radnik smještaj dozvola').trim();state.lastSearch=q;save();document.getElementById('jobs').innerHTML=`<div class="empty">🔎 Consultando fuentes públicas...<br><span class="muted">Esto puede tardar un poco porque se verifica cada portal.</span></div>`;try{const r=await fetch('/api/search?q='+encodeURIComponent(q));const data=await r.json();state.jobs=data.jobs||[];save();render();}catch(e){document.getElementById('jobs').innerHTML=`<div class="notice"><b>No se pudo conectar con el buscador local.</b><br>Si abriste el HTML directamente, inicia el servidor con <code>python server.py</code> y abre <code>http://127.0.0.1:8765</code>.</div>`}finally{btn.disabled=false;btn.innerHTML='<span>⌕</span> Buscar nuevos empleos'}}
function details(i){const j=state.jobs[i];openModal(`<div class="live">EVIDENCIA DE LA OFERTA</div><h2 style="margin-top:8px">${j.title}</h2><p><b>${j.source}</b> · ${j.company} · ${j.city}</p><div class="meta"><span>💰 ${j.salary}</span><span>🏠 ${j.accommodation}</span><span>📄 ${j.permit}</span></div><div class="notice">La clasificación no sustituye la verificación final. Antes de enviar, hay que confirmar específicamente que el alojamiento es gratuito y que el trámite de residencia y trabajo puede hacerse para un colombiano.</div><h3>Texto/evidencia encontrada</h3><div class="message">${j.evidence||'Sin texto disponible'}</div><div class="actions"><a class="primary" target="_blank" href="${j.url}">Abrir fuente original ↗</a></div>`)}
const CRO=`Poštovani,\n\nzainteresiran sam za radno mjesto [RADNO MJESTO] u [GRADU].\n\nDolazim iz Kolumbije i trenutno se nalazim izvan Hrvatske. Imam iskustvo u skladištu, radu s robom, pripremi narudžbi, organizaciji skladišta, dopunjavanju proizvoda i svakodnevnim operativnim poslovima.\n\nOdgovoran sam, vrijedan i prilagodljiv. Dobro radim u timu i imam iskustvo u fizičkom radu.\n\nTakođer me zanima više informacija o uvjetima rada, uključujući mogućnost smještaja koji osigurava poslodavac. Želio bih također potvrditi postoji li mogućnost da poslodavac za državljanina Kolumbije pokrene i provede postupak za izdavanje dozvole za boravak i rad u Hrvatskoj.\n\nU privitku šaljem svoj životopis na hrvatskom jeziku.\n\nHvala na vašem vremenu i očekujem vaš odgovor.\n\nLijep pozdrav,\nYesid Fabián Ramírez Lopez\nfabianramirezlopez216@gmail.com`;
const ESP=`Estimados señores:\n\nEstoy interesado en el puesto de [PUESTO] en [CIUDAD].\n\nSoy de Colombia y actualmente me encuentro fuera de Croacia. Tengo experiencia en almacén, manejo de mercancías, preparación de pedidos, organización de almacenes, reposición de productos y tareas operativas diarias.\n\nSoy responsable, trabajador y adaptable. Trabajo bien en equipo y tengo experiencia realizando trabajo físico.\n\nTambién me gustaría obtener más información sobre las condiciones de trabajo, incluida la posibilidad de alojamiento proporcionado por el empleador. También quisiera confirmar si existe la posibilidad de que el empleador inicie y gestione para un ciudadano colombiano el procedimiento para obtener el permiso de residencia y trabajo en Croacia.\n\nAdjunto mi currículum en croata.\n\nGracias por su tiempo y quedo atento a su respuesta.\n\nSaludos cordiales,\nYesid Fabián Ramírez Lopez\nfabianramirezlopez216@gmail.com`;
function prepare(i){const j=state.jobs[i];state.applications.push({title:j.title,company:j.company,city:j.city,cv:state.cvName,url:j.url,cro:CRO.replace('[RADNO MJESTO]',j.title.split(' (')[0]).replace('[GRADU]',j.city),esp:ESP.replace('[PUESTO]',j.title.split(' (')[0]).replace('[CIUDAD]',j.city)});save();nav('applications')}
function review(i){const a=state.applications[i];openModal(`<div class="live">REVISIÓN</div><h2 style="margin-top:8px">Antes de enviar</h2><div class="notice">🇭🇷 <b>Este es el único mensaje que se enviaría a la empresa.</b></div><div class="message">${a.cro}</div><h3 style="margin-top:18px">🇪🇸 Traducción para ti</h3><div class="message translation">${a.esp}</div><p class="muted">CV adjunto: ${a.cv}</p><div class="actions"><button class="danger" onclick="authorize(${i});closeModalDirect()">Autorizar envío</button><a class="secondary" target="_blank" href="${a.url}">Ver oferta ↗</a></div>`)}
function authorize(i){const a=state.applications[i];openModal(`<div class="live">AUTORIZACIÓN MANUAL</div><h2 style="margin-top:8px">¿Autorizar esta candidatura?</h2><div class="notice">La autorización es independiente de la preparación. En esta versión, todavía no se realiza un envío externo automático.</div><p><b>${a.title}</b><br>${a.company} · ${a.city}</p><div class="actions"><button class="danger" onclick="markAuthorized(${i})">Sí, autorizo</button><button class="secondary" onclick="closeModalDirect()">Cancelar</button></div>`)}
function markAuthorized(i){state.applications[i].status='authorized-demo';save();closeModalDirect();render();alert('Autorización registrada. El envío externo todavía no está conectado.')}
function openModal(html){document.getElementById('modalBody').innerHTML=html;document.getElementById('modal').classList.remove('hidden')}function closeModalDirect(){document.getElementById('modal').classList.add('hidden')}
render();
